language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source --no-suggest --classmap-authoritative $PREFER_LOWEST
  - composer info -i

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
