language: php

env:
  global:
    - COMPOSER_ARGS=

matrix:
  fast_finish: true
  include:
    - php: 7.2
      dist: bionic
      env: deps=low
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      dist: bionic
      env: COMPOSER_ARGS=--ignore-platform-reqs

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - if [ "$deps" == "low" ]; then composer update -n --prefer-dist --prefer-lowest --prefer-stable $COMPOSER_ARGS; fi
  - if [ "$deps" != "low" ]; then composer update -n --prefer-dist $COMPOSER_ARGS; fi
  - composer info -i

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
